### ISSUE TITLE
Add JSON LD for the books

### ISSUE THREAD

**Issue by davorg** [davorg/perlschool#11]

**Comment by briandfoy** [comment]
I'm looking at this. What were you thinking about for organization? Drop into a single folder? One file per author and per book?

I guess I could create the initial stuff and we could move it around later.

**Comment by briandfoy** [comment]
Some examples:

https://schema.org/Book

	<script type="application/ld+json">
		{
		  "@context": "https://schema.org",
		  "@type": "Book",
		  "accessibilityAPI": "ARIA",
		  "accessibilityControl": [
			"fullKeyboardControl",
			"fullMouseControl"
		  ],
		  "accessibilityFeature": [
			"largePrint/CSSEnabled",
			"highContrast/CSSEnabled",
			"resizeText/CSSEnabled",
			"displayTransformability",
			"longDescription",
			"alternativeText"
		  ],
		  "accessibilityHazard": [
			"noFlashingHazard",
			"noMotionSimulationHazard",
			"noSoundHazard"
		  ],
		  "aggregateRating": {
			"@type": "AggregateRating",
			"reviewCount": "0"
		  },
		  "bookFormat": "EBook/DAISY3",
		  "copyrightHolder": {
			"@type": "Organization",
			"name": "Holt, Rinehart and Winston"
		  },
		  "copyrightYear": "2007",
		  "description": "NIMAC-sourced textbook",
		  "genre": "Educational Materials",
		  "inLanguage": "en-US",
		  "isFamilyFriendly": "true",
		  "isbn": "9780030426599",
		  "name": "Holt Physical Science",
		  "numberOfPages": "598",
		  "publisher": {
			"@type": "Organization",
			"name": "Holt, Rinehart and Winston"
		  }
		}
	</script>

https://schema.org/Organization

	<script type="application/ld+json">
	{
	  "@context": "https://schema.org",
	  "@type": "Organization",
	  "address": {
		"@type": "PostalAddress",
		"addressLocality": "Paris, France",
		"postalCode": "F-75002",
		"streetAddress": "38 avenue de l'Opera"
	  },
	  "email": "secretariat(at)google.org",
	  "faxNumber": "( 33 1) 42 68 53 01",
	  "member": [
		{
		  "@type": "Organization"
		},
		{
		  "@type": "Organization"
		}
	  ],
	  "alumni": [
		{
		  "@type": "Person",
		  "name": "Jack Dan"
		},
		{
		  "@type": "Person",
		  "name": "John Smith"
		}
	  ],
	  "name": "Google.org (GOOG)",
	  "telephone": "( 33 1) 42 68 53 00"
	}
	</script>
	
https://schema.org/Person

	<script type="application/ld+json">
	{
	  "@context": "https://schema.org",
	  "@type": "Person",
	  "address": {
		"@type": "PostalAddress",
		"addressLocality": "Seattle",
		"addressRegion": "WA",
		"postalCode": "98052",
		"streetAddress": "20341 Whitworth Institute 405 N. Whitworth"
	  },
	  "colleague": [
		"http://www.xyz.edu/students/alicejones.html",
		"http://www.xyz.edu/students/bobsmith.html"
	  ],
	  "email": "mailto:jane-doe@xyz.edu",
	  "image": "janedoe.jpg",
	  "jobTitle": "Professor",
	  "name": "Jane Doe",
	  "telephone": "(425) 123-4567",
	  "url": "http://www.janedoe.com"
	}
	</script>

**Comment by briandfoy** [comment]
Another example 

* https://github.com/mhausenblas/schema-org-rdf/blob/master/examples/Thing/CreativeWork/Book/Book.jsonld

**Comment by briandfoy** [comment]
Google testing tool

* https://developers.google.com/search/docs/appearance/structured-data

**Comment by briandfoy** [comment]
Reading https://moz.com/blog/json-ld-for-beginners , it sounds like each book page would put its JSON-LD in head (and author pages would put the author LD in there).

**Comment by davorg** [comment]
Now I've confused myself. This ticket was created a year ago, but there's been JSON LD on the site since https://github.com/davorg/perlschool/commit/3a2d90cc7a7d1ab2b91201e2f7c9e32bdbe02e76.

I do think it needs to be improved. In particular, I think I found a way to link a book to its author(s), but not a way to represent the reverse link. That needs more research. Oh, looking in more detail, I see I've only implemented it for books, not on the author page.

The plan was to use the following three types from schema.org:

* https://schema.org/Book (for books)
* https://schema.org/Organization (for Perl School itself)
* https://schema.org/Person (for authors)

But it's possible that there are better schemas for the last two.

It's all implemented with my module [MooX::Role::JSON_LD](https://metacpan.org/pod/MooX::JSON_LD) (as you'll see in [PerlSchool::Schema::Result::Book](https://github.com/davorg/perlschool/blob/master/lib/PerlSchool/Schema/Result/Book.pm).

So, yeah, there's definitely work to be done here. But the basic structure is in place - so I'm sorry if you went down an unnecessary rabbit-hole yesterday.

**Comment by briandfoy** [comment]
No, this is good. I didn't know anything about it before and now I do. I guess I should figure out what sort of Person thing I can provide.

But otherwise I think you can close this issue.

**Comment by davorg** [comment]
Closing this as we have JSON LD for books. I'll raise a few new issues for adding JSON LD to authors and including more data on the pages.
